### ISSUE TITLE
Update on f-droid?

### ISSUE THREAD

**Issue by WPFilmmaker** [tobykurien/WebMediaShare#15]
Latest version on f-droid is from 2018, can you update it? Or should I open a ticket on gitlab at f-droid?

**Comment by tobykurien** [comment]
You can open a ticket. F-droid are currently having issues where apps build successfully but don't show up in the index, so they are manually adding apps at the moment and they may have missed WebMediaShare.


On 3 March 2021 22:33:04 GMT+02:00, WPFilmmaker <notifications@github.com> wrote:
>Latest version on f-droid is from 2018, can you update it? Or should I
>open a ticket on gitlab at f-droid?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebMediaShare/issues/15

-- 
tobykurien.com | @tobykurien
