### ISSUE TITLE
The app is unusable on youtube

### ISSUE THREAD

**Issue by WPFilmmaker** [tobykurien/WebMediaShare#19]
While the app in theory works well on Youtube, in practice it is unusable. When you try to share a video on the app to send it to VLC for example, the user is shown a list of urls to share.

Some of them contain just audio other just videos, trying to understanding what to choose is a nightmare. I would propose to make that when user share the video the list appears however a predefined option is highlighted so the user knows that is the right url to play. In the options one could set a predefined set (for example 1080p audio and video) which could be changed if user wants so.

**Comment by tobykurien** [comment]
This is a known issue which is mentioned in the README file. YouTube (and some other sites) chunks the videos into multiple streams. I recommend using an instance of Invidious (https://api.invidious.io/)  (https://api.invidious.io/)for streaming YouTube, which will give you the option to share the video and/or audio.

--
tobykurien.com | @tobykurien
May 1, 2021 11:58 PM, "WPFilmmaker" ***@***.*** ***@***.******@***.***>)> wrote:
	While the app in theory works well on Youtube, in practice it is unusable. When you try to share a video on the app to send it to VLC for example, the user is shown a list of urls to share.

	Some of them contain just audio other just videos, trying to understanding what to choose is a nightmare. I would propose to make that when user share the video the list appears however a predefined option is highlighted so the user knows that is the right url to play. In the options one could set a predefined set (for example 1080p audio and video) which could be changed if user wants so.

**Comment by WPFilmmaker** [comment]
Thank you for the clarification.
