### ISSUE TITLE
Videos on Youtube

### ISSUE THREAD

**Issue by denialplando** [tobykurien/WebMediaShare#2]
The app works well with Youtube, only you have to play with the user agent properly.

**Comment by tobykurien** [comment]
Thanks @denialplando could you explain what you mean by playing with user agent? While YouTube works in the app, casting to Kodi has been problematic for me.

**Comment by kekukui** [comment]
The following Firefox extensions will now push YouTube links to Kodi successfully if you are using the latest version of the **Kodi YouTube app** (6.5.0).

**Youtube Kodi Cast**
https://github.com/jasenmichael/youtube-kodi-cast

**Echo for Kodi** 
https://github.com/jaylinski/kodi-echo

**Kassi share** 
https://github.com/goldenratio/xbmc-web-remote

**Play to Kodi** 
https://github.com/maciex/play-to-kodi

**Send to Kodi 2**
https://github.com/WPettersson/firefox-send-to-xbmc

**Cast Kodi**
https://github.com/regseb/castkodi

**Kodi Control**
https://github.com/LendoK/kodi-control
(This one will push media links from other sites too, but you may need to play the link in the browser before it will be detected.)
____________

Android alternatives with a _**send to Kodi**_ feature

**NewPipe**
https://github.com/TeamNewPipe/NewPipe/

**Yatse** (invoke the link share feature in your browser, choose "Play on Media Center")
https://yatse.tv/

**Comment by tobykurien** [comment]
If you have the youtube plug-in installed on Kodi, then selecting "Share URL" from the overflow menu will allow you to share and play the video on Kodi.
