### ISSUE TITLE
Media URLs with more than one dot cannot be opened in external media player

### ISSUE THREAD

**Issue by e7appew** [tobykurien/WebMediaShare#4]
I have a simple web server that serves up media files based on the date like this:

2019.03.08.mov

When you open the page in WebMediaShare and long press on the URL, it offers you a selection of external apps that can handle opening URLs, i.e. web browsers only. Missing from this selection are apps that can handle playing media. In my case, VLC.

If, however, I rename the files to contain only a single dot, such as 20190308.mov, VLC is included as an option. It doesn't matter what type of media file it is, if the file name has more than one dot, you won't be given the option to open it in an external media player.

**Comment by e7appew** [comment]
I have done some further testing by installing MX Player as well. It all works as expected with this media player, so it seems like the issue is caused by VLC.

**Comment by tobykurien** [comment]
That is odd. Thanks for reporting. Note that a long press share is different to the cast icon sharing (which tries to share to media players). So you could click the link, then when mov loads, tap the cast icon.
