### ISSUE TITLE
Add option to request device permissions

### ISSUE THREAD

**Issue by Friptick** [tobykurien/WebMediaShare#9]
As per your generous suggestion on discussion of WebApps app:

>One solution is to have a separate fork of WebApps that makes a few concessions, like requesting location, camera, mic, etc. Then your critical apps can run in WebApps, but your media and navigation, etc. can run in the other. Turns out, I already have such a fork: WebMediaShare https://github.com/tobykurien/WebMediaShare - it does not currently request those additional permissions, but that could be added.

Personally most interested in the location permission for maps, but the camera and mic permissions would presumably be useful too.

Thanks for your consideration.

**Comment by tobykurien** [comment]
Closing this issue as location has been implemented in WebApps.
